package com.greenfoxacademy.TeachingMaterialQueryService.Entities.SyllabusAPIEntities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@DynamoDBTable(tableName = "Syllabus")
public class Syllabus {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  private String title;
  private String technology;
  @JsonProperty("weekly-schedule")
  private List<WeeklySchedule> weeklySchedule;

  public Syllabus() {
  }

  public Syllabus(String title, String technology, List<WeeklySchedule> weeklySchedule) {
    this.title = title;
    this.technology = technology;
    this.weeklySchedule = weeklySchedule;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getTechnology() {
    return technology;
  }

  public void setTechnology(String technology) {
    this.technology = technology;
  }

  public List<WeeklySchedule> getWeeklySchedule() {
    return weeklySchedule;
  }

  public void setWeeklySchedule(List<WeeklySchedule> weeklySchedule) {
    this.weeklySchedule = weeklySchedule;
  }

}
