pipeline {
  agent any
  environment {
    REGISTRY = 'greenfox/teaching-material-query-service'
  }

  stages {
    stage('SonarQube') {
      environment {
        scannerHome = tool 'Sonar Scanner'
      }
      steps {
        dir('practice/query'){
          withSonarQubeEnv(installationName: 'Sonar Scanner', credentialsId: 'sonarqube-adambhun') {
            sh '''
              cd practice/query
              chmod +x gradlew
              ./gradlew build -DbuildNumber=$BUILD_NUMBER
            '''
            sh 'cd build && ls -a'
          }
        }
      }
    }
  }
}