pipeline {
  agent any
  environment {
    REGISTRY = 'greenfox/teaching-material-query-service'
  }

  stages {
    stage('SonarQube') {
      environment {
        scannerHome = tool 'Sonar Scanner'
      }
      steps {
        withSonarQubeEnv(installationName: 'Sonar Scanner', credentialsId: 'sonarqube-adambhun') {
          sh '''
            chmod +x gradlew
            ./gradlew build -DbuildNumber=$BUILD_NUMBER
            ./gradlew sonarqube
          '''
        }
      }
    }
  }
}