package com.greenfoxacademy.TeachingMaterialQueryService.Entities.MaterialsAPIEntities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Material")
public class Material {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  private String title;
  private String url;

  public Material() {
  }

  public Material(String title, String url) {
    this.title = title;
    this.url = url;
  }

  public String getId(){
    return id;
  }

  public void setId(String id){
    this.id = id;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }
}
